### ISSUE TITLE
The link from this plugin to the "live demo" is broken.

### ISSUE THREAD

**Issue by ogrotten** [noidexe/top-down-action-rpg-template#2]
On the godot asset store, the link to live demo leads to a page that demands installing a security chrome plugin.

FYI.

**Comment by noidexe** [comment]
Yes, it should be https://redmagegames.com/elcaballerohueco/ now. I've just submitted an edit for approval. 

Thanks for reporting!

**Comment by ogrotten** [comment]
Awesome. It's also on the README.md here.

Also also, Thanks for posting this template. I'm just getting started with godot and it will be very helpful to kinda take this apart and see how some of these things can put together.

**Comment by noidexe** [comment]
Thanks. Just updated README.md.

I'm happy you found it useful. This template was made for students who've never programmed before so it tries to keep everything as simple as possible. You might want to approach things a bit differently for production code but at the same time the simplicity means it's pretty easy to replace any part of the game with your own
